### ISSUE TITLE
Passing PSR3 info into monolog

### ISSUE THREAD

**Issue by nbartley** [splitbrain/php-cli#19]
Quick question,

Is it possible to demonstrate an example of connecting the PSR3CLI extended object to a logger (like monolog). 

passing the initialized logger object into the CLI object creation doesn't work.

**Comment by splitbrain** [comment]
PSR3CLI is itself a PSR3 logger which you can use instead of monolog. This is useful if you use a library in your CLI that expects a PSR logger to output info. By passing the PSR3CLI the libraries output will be sent to STDOUT and be properly colored.

If you want to use Monolog simply use the CLI class and send all your logs directly to monolog.
